server:
  port: ${APPLICATION_HTTP_PORT:0}

spring:
  application:
    name: demo
  profiles:
    active: ${APPLICATION_PROFILE:local}

logging:
  pattern:
    console: "[%level]  [%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}]  %X{traceId:-} %X{spanId:-}  %X{exportable:-}  [${spring.application.name}]  [%logger{0}]  %message%n%xException"

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /api-docs

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
  datasource:
    username: study
    password: docker!!
    connection-test-query: SELECT 1
    url: jdbc:mysql://localhost/study?serverTimezone=Asia/Seoul&characterEncoding=utf8


---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    username: study
    password: docker!!
    connection-test-query: SELECT 1
    url: jdbc:mysql://host.docker.internal/study?serverTimezone=Asia/Seoul&characterEncoding=utf8

