---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    username: study
    password: docker!!
    connection-test-query: SELECT 1
    url: jdbc:mysql://host.docker.internal/study?serverTimezone=Asia/Seoul&characterEncoding=utf8

