---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    username: study
    password: docker!!
    url: jdbc:mysql://host.docker.internal/study?serverTimezone=Asia/Seoul&characterEncoding=utf8


---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    username: study
    password: docker!!
    url: jdbc:mysql://host.docker.internal/study?serverTimezone=Asia/Seoul&characterEncoding=utf8

